config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'login', to: redirect('/auth/gitlab'), as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  resources :repositories, except: %i[destroy show]
  resources :scans, only: %i[create index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  belongs_to :user
  has_many :updated_packages
  validates :name, presence: true
  validates :repo_id, presence: true, uniqueness: true
  validates :web_url, presence: true
  validates :user_id, presence: true
  validates :namespace_path, presence: true
  validates :visibility, presence: true, inclusion: { in: ['public'] }
  validates_associated :user
end

app/models/updated_package.rb
# frozen_string_literal: true

class UpdatedPackage < ApplicationRecord
  belongs_to :repository
  validates :name, presence: true
  validates :package_manager, presence: true
  validates :previous_version, presence: true
  validates :current_version, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates_presence_of :provider, :gid, :email, :fullname, :handle, :picture, :access_token
  has_many :repositories

  def self.find_or_create_from_auth_hash(auth)
    where(provider: auth.provider, gid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.gid = auth.uid
      user.bio = auth.extra.raw_info.bio
      user.email = auth.info.email
      user.fullname = auth.info.name
      user.handle = auth.info.username
      user.picture = auth.info.image
      user.access_token = auth.credentials.token

      user.save!
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery with: :exception

  def authenticate
    redirect_to :login unless user_signed_in?
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    redirect_to repositories_path if user_signed_in?
  end
end

app/controllers/repositories_controller.rb
# frozen_string_literal: true

class RepositoriesController < ApplicationController
  before_action :authenticate

  def index
    @repositories = current_user.repositories
    @pagination = paginate_repos_from_gitlab_response_headers(projects_response.headers)
  end

  def create
    projects = JSON.parse(projects_response).select { |project| project['visibility'] == 'public' }
    projects.each do |project|
      next if current_user.repositories.find_by(repo_id: project['id'])

      current_user.repositories.create(scan: false, name: project['name'], repo_id: project['id'],
                                       description: project['description'],
                                       visibility: project['visibility'],
                                       web_url: project['web_url'],
                                       namespace_path: project['path_with_namespace'])
    end
    redirect_to repositories_path
  end

  def update
    @repository = current_user.repositories.find(params[:id])
    if @repository['scan'] == true
      @repository.update_attribute(:scan, false)
    else
      @repository.update_attribute(:scan, true)
    end
    redirect_to repositories_path
  end

  private

  def projects_response
    GitlabRepoService.new(current_user).fetch_user_projects(params[:page])
  end
end

app/controllers/scans_controller.rb
# frozen_string_literal: true

class ScansController < ApplicationController
  def index
    @repositories = current_user.repositories.where(scan: true)
  end

  def create
    @repositories = current_user.repositories.where(scan: true)
    @repositories.each do |repository|
      repository.updated_packages.delete_all
      access_token = repository.user.access_token
      namespace_path = repository.namespace_path
      updated_packages = dependabot_service(access_token, namespace_path)
      next unless updated_packages

      add_package_details(updated_packages, repository)
    end
    redirect_to scans_path
  end

  private

  def dependabot_service(token, path)
    DependabotService.new(token, path).run
  end

  def add_package_details(updated_packages, repository)
    updated_packages.each do |updated_package|
      updated_package.each do |package|
        repository.updated_packages.create(name: package.name,
                                           package_manager: package.package_manager,
                                           previous_version: package.previous_version,
                                           current_version: package.version)
      end
    end
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth_hash(request.env['omniauth.auth'])
    session[:user_id] = @user.id
    redirect_to repositories_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    !current_user.nil?
  end

  def paginate_repos_from_gitlab_response_headers(headers)
    {
      next: headers[:x_next_page],
      prev: headers[:x_prev_page],
      total_pages: headers[:x_total_pages],
      total: headers[:x_total],
      per_page: headers[:x_per_page]
    }
  end
end

app/views/home/index.html.erb
<div class="has-text-centered">
<h1 class="has-text-weight-bold">Gitlab Dependabot Example</h1>
<p class="has-text-weight-medium">This application showcase an implementation of dependabot for Gitlab</p>
<p class="tag is-danger is-light has-text-weight-medium"><strong>PS:</strong> Now the app only scans dependencies of Bundler package manager. support for other package managers are in roadmap</span></p>
</div>
<figure class="image is-4by3">
 <%= image_tag "dashboard.png" %>
</figure>

<figure class="image is-200x200">
<%= image_tag "scan_results.png" %>
</figure>

app/views/layouts/_pagination.html.erb
<nav class="pagination" role="navigation" aria-label="pagination">
  <a href="<%= repositories_path(:page => @pagination[:prev]) %>" class = "pagination-previous">Previous</a>
  <a href="<%= repositories_path(:page => @pagination[:next]) %>" class = "pagination-next">Next</a>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <title>Project Pipe</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.0/css/bulma.min.css">
</head>
<body class="has-background-light">

  <nav class="navbar is-transparent" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <%= image_tag "rocket.svg" %>&nbsp;Gitlab Dependabot Example
      </a>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbar-menu">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbar-menu" class="navbar-menu">


      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <% if user_signed_in? %>
            <span class="has-text-weight-medium mr-2"><%= @current_user.fullname %></span>
              <a class="button is-danger" href="/logout">
                Logout
              </a>
            <% else %>
              <a class="button is-success" href="/login">
                Log in with GitLab
              </a>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <section class="section">
      <%= yield %>
  </section>
</body>
</html>

app/views/repositories/index.html.erb
<div class="columns">
  
  <% if @repositories.empty? %>
  <div class="column has-text-centered is-half is-offset-one-quarter">
    <%= button_to "import repositories", repositories_path, class: "button is-link" %>
    <p class="is-size-7 mt-1">Click to import your repositories from Gitlab.</p>
  </div>
  <% else %>
  <div class="column has-background-white has-text-centered is-half is-offset-one-quarter">
    <h1 class="title">Add your repos from Gitlab</h1>
    <p>Select which repositories to start scanning (supports only <strong>Bundler</strong> as of now)</p>
    <span class="tag is-primary is-light mt-1">Found <%= @repositories.length %> Public repositories</span>
    <%= button_to "Refresh repositories", repositories_path, class: "button is-link is-outlined is-small mt-1", span_class: "icon" %>
    <hr>
    <% if !@repositories.blank? %>
      <% for repository in @repositories %>
      <div class="container level">

        <div class="level-left">
          <div class="level-item">
            <p><strong><%= repository['name'] %></strong></p>
          </div>
          <div class="level-item">
            <span class="icon">
              <i class="fa fa-unlock-alt"></i>
            </span>
          </div>
          <div class="level-item">
            <a href="<%= repository['web_url'] %>">
            <span class="icon">
              <i class="fa fa-link"></i>
            </span>
            </a>
          </div>
        </div>

        <div class="level-right">
          <% if repository['scan'] == true %>
            <%= button_to "remove from scanner", repository_path(repository), class: "button is-danger is-small", method: :put %>
          <% else %>
            <%= button_to "add to scanner", repository_path(repository), class: "button is-link is-small", method: :put %>
          <% end %>
        </div>
      </div>
      <hr>
        <% end %>
      <%= button_to "start scan", scans_path, class: "button is-link is-small", method: :post %>
      <p>Ps: It'll take a few minutes before the scan ends, please wait.</p>
    <% else %>
    <div class="column">No repositorys found!</div>
  </div>
  <% end %>
  <br>
  <% end %>
</div>

app/views/scans/index.html.erb
<div class="columns">
    <% @repositories.each do |repository| %>
    <div class="column has-background-dark has-text-centered has-text-white is-half is-offset-one-quarter">

    <p><strong class="has-text-white"><%= repository['name'] %></strong>        
        <a href="<%= repository['web_url'] %>">
        <span class="icon has-text-success">
          <i class="fa fa-link"></i>
        </span>
        </a>
    </p> 
    <% if !repository.updated_packages.empty? %>
        <% repository.updated_packages.each do |package|%> 

         <p>updated <%= package['name'] %> from <%= package['previous_version'] %> 
            to <%= package['current_version'] %> (<%= package['package_manager'] %>)</p>   

        <% end %>
        <br>
        <span class="has-text-success">Completed scanning!</span>
    <% else %>
        <li><span class="has-text-success">Repository might be empty!</span></li>
    <br>
    <% end %>
    </div>
</div>
<% end %>